services:
  contracts:
    build:
      context: ./contracts/inft
    container_name: ai-influencer-contracts
    restart: unless-stopped
    env_file:
      - ./contracts/inft/.env
    volumes:
      - ./contracts/inft:/app
    command: npx hardhat node
    ports:
      - "8545:8545"
    working_dir: /app

  backend:
    build: ./backend
    container_name: ai-influencer-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/shared:/app/shared
      - ./backend:/app
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - contracts